### ISSUE TITLE
def parse_bc won't read barcodes

### ISSUE THREAD

**Issue by malvarez227** [thomasvangurp/epiGBS#1]
Prints a length of zero at the end - it looks like it's not properly reading the barcodes into the bc_dict dictionary, resulting in an empty dictionary. I'm attaching our barcodes file in .csv format, but we've tried tab-delimited as well. This results in empty files created at the end of the script.

[barcodes.csv.zip](https://github.com/thomasvangurp/epiGBS/files/93075/barcodes.csv.zip)

**Comment by malvarez227** [comment]
Scratch that, solved by updating line 217 to:
    file_in = open(barcodes, 'rU')

also, had to feed it a tab-delineated file, although it defaults to a .csv file.

**Comment by thomasvangurp** [comment]
I'm reworking many of the scripts to make sure dependency and other issues are tackled.
